### ISSUE TITLE
Turn into an autoplugin

### ISSUE THREAD

**Issue by nrinaudo** [sbt/sbt-unidoc#30]
I've actually started working on that and created the issue to start a discussion. While adapting the plugin, I realised that unidoc actually provides two different sets of settings:
- `scalaUnidocSettings`
- `scalaJavaUnidocSettings`

My first instinct, but I'd like to confirm that it's alright, is to provide two auto plugins, one per set of settings:
- `UnidocPlugin`
- `UnidocJavaPlugin`

Is that the right course?

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt-unidoc actually lists more:

- add unidocSettings to root (how to unify Scaladoc)
- add genjavadocSettings to children, javaUnidocSettings to root (how to unify javadoc)
- add genjavadocExtraSettings to children (how to publish genjavadoc instead of scaladoc)
- add genjavadocSettings or genjavadocExtraSettings to children, scalaJavaUnidocSettings to root (how to unify both Scaladoc and Javadoc)

**Comment by nrinaudo** [comment]
Ah, that's going to be quite a bit more involved than I expected :)
